format = """
[](#44475a)\
$directory\
[](fg:#44475a bg:#6272a4)\
$git_branch\
$git_status\
[](fg:#6272a4 bg:#BD93F9)\
$golang\
$java\
$julia\
$nodejs\
$rust\
[ ](fg:#BD93F9)\
"""
right_format = """
[](fg:#44475a)
$time
[](fg:#44475a)
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'

[directory]
style = "bg:#44475a"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = " "

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:#6272a4"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#6272a4"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#8FBCBB"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#8FBCBB"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#8FBCBB"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#BD93F9"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#8FBCBB"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#44475a"
format = '[  $time ]($style)'
